package com.avioconsulting.mule.connector.vault.provider.api.connection.impl;

import com.avioconsulting.mule.connector.vault.provider.api.parameter.EngineVersion;
import com.avioconsulting.mule.connector.vault.provider.api.parameter.SSLProperties;
import com.bettercloud.vault.SslConfig;
import com.bettercloud.vault.Vault;
import com.bettercloud.vault.VaultConfig;
import com.bettercloud.vault.VaultException;
import com.bettercloud.vault.response.AuthResponse;
import org.mule.runtime.api.connection.ConnectionException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.Clock;

/**
 * A connection to Vault using EC2 properties for authentication
 *
 * @author Adam Mead
 */
public class Ec2VaultConnection extends AbstractVaultConnection {

    private final Logger LOGGER = LoggerFactory.getLogger(Ec2VaultConnection.class);

    /**
     * Construct a connection to Vault using EC2 properties
     *
     * @param id             ID for the connection
     * @param vaultUrl       URL for the Vault server (https://host:port)
     * @param role           The Vault role to use for authentication
     * @param pkcs7          PKCS7 signature of the identity document with all \n characters removed
     * @param nonce          Client nonce used for authentication. If null, a new nonce will be generated by Vault
     * @param identity       Base64 encoded EC2 instance identity document.
     * @param signature      Base64 encoded SHA256 RSA signature of the instance identity document.
     * @param awsAuthMount   AWS auth mount
     * @param sslProperties  {@link SSLProperties} to use to make the connection
     * @param engineVersion  The version of the secret engine to use, defaulting to Version 2
     * @throws ConnectionException
     */
    public Ec2VaultConnection(String id, String vaultUrl, String role, String pkcs7, String nonce, String identity,
                              String signature, String awsAuthMount, SSLProperties sslProperties,
                              EngineVersion engineVersion) throws ConnectionException {
        this.id = id;
        this.vaultConfig = new VaultConfig().address(vaultUrl);
        if (engineVersion != null) {
            this.vaultConfig = this.vaultConfig.engineVersion(engineVersion.getEngineVersionNumber());
        }
        try {
            SslConfig ssl = getVaultSSLConfig(sslProperties);
            this.vaultConfig = this.vaultConfig.sslConfig(ssl.build());
            Vault vaultDriver = new Vault(this.vaultConfig.build());
            AuthResponse response = null;
            if (pkcs7 != null) {
                response = vaultDriver.auth().loginByAwsEc2(role, pkcs7, nonce, awsAuthMount);
            } else {
                response= vaultDriver.auth().loginByAwsEc2(role, identity, signature, nonce, awsAuthMount);
            }
            this.vaultConfig = this.vaultConfig.token(response.getAuthClientToken());
            this.renewable = response.getRenewable();
            this.expirationTime = Clock.systemDefaultZone().instant().plusSeconds(response.getAuthLeaseDuration());
            this.vault = new Vault(this.vaultConfig.build());
            this.valid = true;
        } catch (VaultException ve) {
            LOGGER.error("Error connecting to Vault", ve);
            throw new ConnectionException(ve);
        }
    }

}
